name: front
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  intl: ^0.20.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 

flutter:
  uses-material-design: true
  assets:
    - assets/images/model_a.png
    - assets/images/model_b.jpg
    - assets/images/model_c.jpg
    - assets/images/model_d.png
    - assets/images/default_avatar.jpg
    - assets/images/anime_girl.jpg
    - assets/images/anime_girl_register.jpg